Update to work with chromedriver >= 2.39, build script fix for Windows
webdriverio/wdio-devtools-service pull request #11
Opened 2018-06-10 11:23 UTC by Eduard-iCH

Tested both on macOS and Windows 7.

By the way - chrome://vesrion is empty in headless mode. So still need to find a better way.

2018-06-13 10:07 UTC, christian-bromann requested changes
This is awesome, thanks so much 👍 .. this package is already ported to [v5](https://github.com/webdriverio/v5/tree/master/packages/wdio-devtools-service). Do you mind creating a PR for this too?

2018-06-13 10:10 UTC, Eduard-iCH commented
Yes, i can port it in 0-2 days.

2018-06-13 10:13 UTC, christian-bromann commented
> Yes, i can port it in 0-2 days. Need to install v5.

There is a Contribution.md that should help you getting started, if you have any issues, let us know in the v5 gitter channel. Thanks!

2018-08-30 09:42 UTC, christian-bromann commented
@Eduard-iCH I ported the change to v5. You only need to sign the CLA to get this merged. Thanks!

2018-09-21 18:26 UTC, mauricioardiles-ml commented
Hi, is there any change to get this fix for Mac and Linux ?

2018-09-22 09:48 UTC, christian-bromann commented
@Eduard-iCH would you mind signing the CLA so I can merge this?

2018-10-08 07:28 UTC, mansn commented
Isn't this PR pretty much the same thing that was done in this commit: https://github.com/webdriverio-boneyard/wdio-devtools-service/commit/f89f75009c7a39fafe3b4b0c7079d456e24df73e ?

2018-11-06 10:34 UTC, christian-bromann commented
> Isn't this PR pretty much the same thing that was done in this commit: [f89f750](https://github.com/webdriverio-boneyard/wdio-devtools-service/commit/f89f75009c7a39fafe3b4b0c7079d456e24df73e) ?

Yes, closing.

2018-11-06 10:34 UTC, closed without merging